### PR TITLE
Updated daemon command, failed otherwise

### PR DESCRIPTION
**Pull request by softmodal**
This is the first time I've used osrm-routed, so I'm not sure if I missed something or if its syntax has changed, but I had to put the config file as an option after the map file in the daemon variable.

orsm_routed_help

### CODE REVIEW

**Comment by chr4** [comment]
I experienced this issue myself, but then couldn't reproduce it. Will review it next week, thanks for the contribution!

Can you quickly post which version of osrm you're using?

**Comment by softmodal** [comment]
I'm using the recipe default of v0.4.1. It took a long time to extract and prepare North America, but I may build a new server with the latest. I'll reply back with any news.

**Comment by chr4** [comment]
Current version is 4.5.0, guess a general udpate would be nice, too.

**Comment by softmodal** [comment]
Sorry for the late reply. I updated my fork to point to the new repository and updated the branch attribute to master. I had to also update install_git.rb to include the new required packages.

Once I did that I was able to install, extract, and prepare OSRM v4.5.0. I tried the daemon command both ways and was only able to get it to work with the latest syntax.

FWIW, going from from 4.1 to 4.5 shaved several hours off extract/prepare for North America.

**Comment by chr4** [comment]
Closing this, upcoming v5.0.0 should fix all issues.

**Pull request closed without merging**
